project:
  type: book

book:
  title: "Guía de Proyeccion Econométrica"
  author: "Francisco Orlando Rosales"
  date: "05/4/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - cap1.qmd
    - cap2.qmd
    - cap3.qmd
    - cap4.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

