<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Modelo Poisson – Guía de Proyeccion Econométrica</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./cap4.html" rel="next">
<link href="./cap2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./cap3.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelo Poisson</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Guía de Proyeccion Econométrica</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Resumen</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variable dependiente binaria</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelo Tobit</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelo Poisson</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelo de Dos Partes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción-y-motivación" id="toc-introducción-y-motivación" class="nav-link active" data-scroll-target="#introducción-y-motivación"><span class="header-section-number">5.1</span> Introducción y motivación</a>
  <ul class="collapse">
  <li><a href="#recordatorio" id="toc-recordatorio" class="nav-link" data-scroll-target="#recordatorio"><span class="header-section-number">5.1.1</span> Recordatorio</a></li>
  <li><a href="#otro-ejemplo" id="toc-otro-ejemplo" class="nav-link" data-scroll-target="#otro-ejemplo"><span class="header-section-number">5.1.2</span> Otro ejemplo</a></li>
  </ul></li>
  <li><a href="#ejemplo-regresión-de-poisson-para-número-de-arrestos" id="toc-ejemplo-regresión-de-poisson-para-número-de-arrestos" class="nav-link" data-scroll-target="#ejemplo-regresión-de-poisson-para-número-de-arrestos"><span class="header-section-number">5.2</span> Ejemplo [Regresión de Poisson para número de arrestos]</a>
  <ul class="collapse">
  <li><a href="#estimación-de-sigma2" id="toc-estimación-de-sigma2" class="nav-link" data-scroll-target="#estimación-de-sigma2"><span class="header-section-number">5.2.1</span> Estimación de <span class="math inline">\(\sigma^2\)</span></a></li>
  <li><a href="#ajustar-los-errores-estándar" id="toc-ajustar-los-errores-estándar" class="nav-link" data-scroll-target="#ajustar-los-errores-estándar"><span class="header-section-number">5.2.2</span> Ajustar los errores estándar</a></li>
  <li><a href="#interpretación" id="toc-interpretación" class="nav-link" data-scroll-target="#interpretación"><span class="header-section-number">5.2.3</span> Interpretación</a></li>
  <li><a href="#efectos-marginales-de-la-regresión-exponencial-emcv-poisson" id="toc-efectos-marginales-de-la-regresión-exponencial-emcv-poisson" class="nav-link" data-scroll-target="#efectos-marginales-de-la-regresión-exponencial-emcv-poisson"><span class="header-section-number">5.2.4</span> Efectos marginales de la Regresión Exponencial EMCV-Poisson</a></li>
  <li><a href="#interpretaciones" id="toc-interpretaciones" class="nav-link" data-scroll-target="#interpretaciones"><span class="header-section-number">5.2.5</span> Interpretaciones:</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelo Poisson</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introducción-y-motivación" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="introducción-y-motivación"><span class="header-section-number">5.1</span> Introducción y motivación</h2>
<p>Una tercera clase de variable dependiente no negativa es una <strong>variable de conteo</strong>, que puede asumir valores enteros no negativos: <span class="math inline">\([0,1,2,...]\)</span>, específicamente los que nos interesa son los casos en los que <span class="math inline">\(y\)</span> asume pocos valores, incluido el cero. Ejemplos:</p>
<ul>
<li><p>El número de medallas que puede obtener un deportista en una olimpiada,</p></li>
<li><p>El número de hijos que tiene una mujer</p></li>
<li><p>El número de publicaciones al año de un científico</p></li>
</ul>
<p>Al igual que las respuestas, binaria y Tobit, un modelo lineal para <span class="math inline">\(E(y|x_1,x_2,...,x_k)\)</span>, quizá no proporciona el mejor ajuste a lo largo de todos los valores de las variables explicativas. Sin embargo, es informativo comenzar con un modelo lineal.</p>
<p>Como en un modelo <strong>Tobit</strong> no se puede obtener el logaritmo de una variable de conteo que asume valores de cero. Un método útil es modelar el valor esperado como una función exponencial:</p>
<p><span class="math display">\[E(y|x_1,x_2,...,x_k)=exp(\beta_0+\beta_1x_1+...+\beta_kx_k)\ [1]\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(wooldridge, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               stargazer, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="recordatorio" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="recordatorio"><span class="header-section-number">5.1.1</span> Recordatorio</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"wage1"</span>, <span class="at">package =</span> <span class="st">"wooldridge"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelo lineal</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>salario.lm<span class="ot">&lt;-</span><span class="fu">lm</span>(wage<span class="sc">~</span>educ,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>               wage1)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(salario.lm, </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                               wage            
-----------------------------------------------
educ                         0.541***          
                              (0.053)          
                                               
Constant                      -0.905           
                              (0.685)          
                                               
-----------------------------------------------
Observations                    526            
R2                             0.165           
Adjusted R2                    0.163           
Residual Std. Error      3.378 (df = 524)      
F Statistic          103.363*** (df = 1; 524)  
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfica de la relación salario y la educación</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wage<span class="sc">~</span>educ, </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>     wage1,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"steelblue"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Salario en USD por hora"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"años de educación"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"La relación entre el salario y la educación"</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(salario.lm, </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">lw=</span><span class="dv">2</span>,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap3_files/figure-html/no-lineal-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y=</span>wage1<span class="sc">$</span>wage,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">x=</span>wage1<span class="sc">$</span>educ,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"blue"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">19</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Años de educación"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Salario en USD/hora"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap3_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretaciones</strong></p>
<ul>
<li>Un aumento de un año de educación, esta asociado en promedio a un incremento en el salario de 54 centavos por cada trabajada.</li>
</ul>
<p>Es decir que la forma funcional al parecer, es la siguiente:</p>
<p><span class="math display">\[wage=exp(\beta_0+\beta_1educ+u)\ [2]\]</span></p>
<p>La ecuación [2] no es lineal en los parámetros, para usar el modelo de regresión se usa un cambio usando la función logarítmica, tenemos:</p>
<p><span class="math display">\[log(wage)=\beta_0+\beta_1educ+u\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>log.lin<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="fu">log</span>(wage)<span class="sc">~</span>educ,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>            wage1)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(log.lin, </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                             log(wage)         
-----------------------------------------------
educ                         0.083***          
                              (0.008)          
                                               
Constant                     0.584***          
                              (0.097)          
                                               
-----------------------------------------------
Observations                    526            
R2                             0.186           
Adjusted R2                    0.184           
Residual Std. Error      0.480 (df = 524)      
F Statistic          119.582*** (df = 1; 524)  
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p><strong>Intepretación</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(log.lin)[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   1.792789 </code></pre>
</div>
</div>
<ul>
<li><p><span class="math inline">\(e^{0.584}=1.79\)</span> Si no hay cambios en la educación, se predice un ingreso promedio por hora trabajada de 1.79 USD</p></li>
<li><p>Un aumento de un año en la educación esta asociado a un incremento de 8.3% en el salario por hora trabajada</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfica de la relación salario y la educación</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(wage)<span class="sc">~</span>educ, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>     wage1,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"steelblue"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Salario en USD por hora"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"años de educación"</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"La relación entre el salario y la educación"</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(log.lin,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">lw=</span><span class="dv">2</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"green"</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(salario.lm,</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"red"</span>,</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap3_files/figure-html/grafica-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="otro-ejemplo" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="otro-ejemplo"><span class="header-section-number">5.1.2</span> Otro ejemplo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"CASchools"</span>, <span class="at">package =</span> <span class="st">"AER"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>Notas<span class="ot">&lt;-</span>(CASchools<span class="sc">$</span>read<span class="sc">+</span>CASchools<span class="sc">$</span>math)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>lineal.model<span class="ot">&lt;-</span><span class="fu">lm</span>(Notas<span class="sc">~</span>income,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                 CASchools)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>lineal.log<span class="ot">&lt;-</span><span class="fu">lm</span>(Notas<span class="sc">~</span><span class="fu">log</span>(income),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>               CASchools)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Notas<span class="sc">~</span>income,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>     CASchools,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"steelblue"</span>,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Linea de regresión Notas-ingreso"</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>order_id2<span class="ot">&lt;-</span><span class="fu">order</span>(CASchools<span class="sc">$</span>income)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(CASchools<span class="sc">$</span>income[order_id2],</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>      <span class="fu">fitted</span>(lineal.log)[order_id2],</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">col=</span><span class="st">"green"</span>, </span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(lineal.model,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"red"</span>,</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap3_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Volviendo a la ecuación [1], debido a que <span class="math inline">\(exp(.)\)</span> siempre es positivo. [1] asegura que los valores predichos para <span class="math inline">\(y\)</span> también sean positivos. Aunque [1] es más complicada que un modelo lineal, básicamente ya se sabe como interpretar los coeficientes, al obtener el logaritmo de la ecuación [1]</p>
<p><span class="math display">\[log[E(y|x_1,...,x_k)]=\beta_0+\beta_1x_1+...+\beta_kx_k\ [2]\]</span> es decir, que el logaritmo del valor esperado es lineal. Por lo tanto, mediante las propiedades de la aproximación de la función logaritmo tenemos:</p>
<p><span class="math display">\[\%\Delta E(y|\mathbf{x})\approx(100\beta_j)\Delta x_j[3]\]</span> Es decir, <span class="math inline">\(100\beta_j\)</span> es el cambio porcentual en <span class="math inline">\(E(y|\mathbf{x})\)</span>, dado un incremento de una unidad en <span class="math inline">\(x_j\)</span>. A veces, es necesaria una estimación más precisa y es fácil de encontrar una, al observar los cambios discretos en el valor esperado. Manteniendo todas la variables explicativas fijas, excepto <span class="math inline">\(x_j\)</span> y, sea <span class="math inline">\(x_k^0\)</span> el valor inicial y <span class="math inline">\(x_k^1\)</span> el valor siguiente. Entonces, el cambio proporcional en el valor esperado es:</p>
<p><span class="math display">\[[exp(\beta_o+\mathbf{x_{k-1}\beta_{k-1}}+\beta_kx_k^1)/exp(\beta_o+\mathbf{x_{k-1}\beta_{k-1}}+\beta_kx_k^0)]-1=exp(\beta_k\Delta{x_k})-1\ [4]\]</span></p>
<p>Donde: <span class="math inline">\(\mathbf{x_{k-1}\beta_{k-1}}\)</span> es una abreviatura de <span class="math inline">\(\beta_1x_1+..+\beta_{k-1}x_{k-1}\)</span> y, <span class="math inline">\(\Delta{x_k}=x_k^1-x_k^0\)</span>. Cuando <span class="math inline">\(\Delta{x_k}=1\)</span>, la variable <span class="math inline">\(x_k\)</span> es binaria que se cambia de cero a uno, entonces el cambio es <span class="math inline">\(exp(\beta_k)-1\)</span>. Dada <span class="math inline">\(\widehat{\beta}_k\)</span>, se obtiene <span class="math inline">\(exp(\widehat{\beta}_k)-1\)</span> y se multiplica por el 100 para transformar el cambio proporcional en un cambio porcentual.</p>
<p>Si por ejemplo <span class="math inline">\(x_j=log(z_j)\)</span> para alguna variable <span class="math inline">\(z_j&gt;0\)</span>, entonces su coeficiente <span class="math inline">\(\beta_j\)</span> se interpreta como una elasticidad respecto a <span class="math inline">\(z_j\)</span></p>
<p>Debido a que [1] es no lineal en sus parámetros, no se puede usar métodos de regresión lineal. Entonces usamos la <strong>estimación máxima verosimilitud (EMV)</strong> y también el método relacionado a la <strong>estimación de cuasi máxima verosimilitud (ECMV)</strong></p>
<p>A lo largo de los cursos de econometría se ha presentado la normalidad como el supuesto de distribución estándar para regresión lineal. Este supuesto no puede usarse en una variable de conteo (pues la distribución normal es para variables continuas que asuman todos los valores) que asume sólo pocos valores, la distribución será muy distinta a la normal. En su lugar, la distribución nominal para los datos de conteo es la <strong>distribución Poisson</strong></p>
<p>Como nos interesa el efecto de las variables explicativas sobre <span class="math inline">\(y\)</span>, se debe observar la distribución de Poisson condicional a <span class="math inline">\(\mathbf{x}\)</span>. La distribución Poisson está determinada por completo por su media, así sólo se necesita especificar <span class="math inline">\(E(y|\mathbf{x})\)</span>, esta tiene la misma forma de [1] que se abrevia <span class="math inline">\(exp(\mathbf{x\beta})\)</span>. Entonces, la probabilidad de que <span class="math inline">\(y\)</span> será igual al valor <span class="math inline">\(h\)</span>, condicional sobre <span class="math inline">\(\mathbf{x}\)</span>, es:</p>
<p><span class="math display">\[P(y=h|\mathbf{x})=exp[-exp(\mathbf{x\beta})][exp(\mathbf{x\beta})]^h/h!, h=0,1,...\ [5]\]</span> Donde <span class="math inline">\(h!\)</span> denota el factorial. Esta distribución, que es la base del <strong>modelo de regresión de Poisson</strong>, permite hallar las probabilidades condicionales para cualquier valor de variables explicativas. Por ejemplo, <span class="math inline">\(P(y=0|\mathbf{x})=exp[-exp(\mathbf{x\beta})]\)</span>. Una vez que se tienen las estimaciones de <span class="math inline">\(\beta_j\)</span>, se pueden insertar en las probabilidades para diferentes valores <span class="math inline">\(\mathbf{x}\)</span>.</p>
<p>Dada una muestras aleatoria <span class="math inline">\([(\mathbf{x_i},y_i):i=1,2,...,n]\)</span>, se puede construir la función <strong>log-verosimilitud</strong>:</p>
<p><span class="math display">\[\mathcal{L(\beta)}=\Sigma_{i=1}^n\mathcal{l_i(\beta)}=\Sigma_{i=1}^n[y_i\mathbf{x_i\beta}-exp(\mathbf{x_i\beta})]\ [6]\]</span> Se desecha el término <span class="math inline">\(log(y_i!)\)</span>. Esta función se maximiza usando EMV, aunque la EMV de Poisson no es cerrada.</p>
<p>Igual que los modelo logit, probit y Tobit, no se pueden comparar directamente las magnitudes de las estimaciones del Poisson de una función exponencial con las estimaciones de MCO. se hace comparables de la siguiente forma:</p>
<section id="variables-explicativas-continuas" class="level4" data-number="5.1.2.1">
<h4 data-number="5.1.2.1" class="anchored" data-anchor-id="variables-explicativas-continuas"><span class="header-section-number">5.1.2.1</span> Variables explicativas continuas</h4>
<p>Se aplica el efecto parcial de <span class="math inline">\(x_j\)</span> respecto a <span class="math inline">\(E(y|x_1,x_2,..,x_k)\)</span>:</p>
<p><span class="math display">\[\frac{\partial E(y|x_1,x_2,..,x_k)}{\partial x_j}=exp(\beta_0+\beta_1x_1+...+\beta_kx_k)\times \beta_j [7]\]</span> Es interesante el factor escalar <strong>EPP</strong>:</p>
<p><span class="math display">\[n^{-1}\Sigma_{i=1}^nexp(\hat{\beta}_0+\hat{\beta}_1x_1+...+\hat{\beta}_kx_k)=n^{-1}\Sigma_{i=1}^n\hat{y}_i [8]\]</span></p>
<p>es simplemente el promedio muestral <span class="math inline">\(\bar{y}\)</span> de <span class="math inline">\(y_i\)</span> donde se definen los valores ajustados como <span class="math inline">\(\widehat{y}_i=exp(\hat{\beta}_0+\mathbf{x_i\hat{\beta}})\)</span>. Es decir, para la regresión Poisson con una función media exponencial, el promedio de los valores ajustados es el mismo que el promedio de los resultados originales de <span class="math inline">\(y_t\)</span>, tal como el caso de regresión lineal. Esto simplifica el escalar de las estimaciones Poisson <span class="math inline">\(\widehat{\beta}_j\)</span>, para hacerlas comparables a las estimaciones MCO, <span class="math inline">\(\widehat{\gamma}_j\)</span> para una variable explicativa continua, se puede comparar con <span class="math inline">\(\widehat{\gamma}_j\)</span> con <span class="math inline">\(\bar{y}.\widehat{\beta}_{j}\)</span></p>
<p>Aunque el análisis de EMV de Poisson es un primer paso para los datos de conteo, suele ser muy restrictivo. Todas las probabilidades y los momentos mayores de la distribución Poisson se determinan por completo por la media. Por ejemplo, la varianza es igual a la media:</p>
<p><span class="math display">\[Var(y|\mathbf{x})=E(y|\mathbf{x})\hspace{0.5cm} [9]\]</span> Esto es restrictivo y se viola en muchas aplicaciones. Por fortuna, la distribución de Poisson tiene una propiedad de robustez muy buena, es decir, que se mantenga o no la distribución de Poisson, se obtienen estimadores asistóticamente normales y consistentes con las <span class="math inline">\(\beta_j\)</span></p>
<p>Cuando se EMV de Poisson, pero no se supone que la distribución de Poisson sea correcta, este análisis recibe el nombre de <strong>Estimación de cuasi máxima verosimilitud (ECMV)</strong>. LA ECMV de Poisson es muy útil debido a que esta programada en muchos paquetes econométricos. Sin embargo, a menos que el supuesto de varianza de Poisson [9] se mantenga, se deben ajustar los errores estándar, de la siguiente forma:</p>
<p>El ajuste a los errores estándar está disponible cuando se supone que la varianza es proporcional a la media:</p>
<p><span class="math display">\[Var(y|\mathbf{x})=\sigma^2E(y|\mathbf{x})\ [10]\]</span> Donde: <span class="math inline">\(\sigma^2\)</span> es un parámetro desconocido.</p>
<ul>
<li><p>Cuando <span class="math inline">\(\sigma^2=1\)</span> se obtiene el supuesto de varianza de Poisson [9]</p></li>
<li><p>Si <span class="math inline">\(\sigma^2&gt;1\)</span> la varianza es mayor que la media para toda <span class="math inline">\(\mathbf{x}\)</span>, esto se llama <strong>sobredispersión</strong> común en regresiones de conteo.</p>
<ul>
<li>Si <span class="math inline">\(\sigma^2&lt;1\)</span> la varianza es menor que la media para toda <span class="math inline">\(\mathbf{x}\)</span>, esto se llama <strong>subdispersión</strong> es poco común.</li>
</ul></li>
</ul>
<p>Bajo [10] es fácil ajustar los errores estándar de la EMV de Poisson. Si <span class="math inline">\(\hat{\beta}_j\)</span> denota la ECMV de Poisson y se definen los residuales como <span class="math inline">\(\hat{u}_i=y_i-\hat{y}_i\)</span>, donde <span class="math inline">\(\hat{y}_i=exp(\hat{\beta}_0+\hat{\beta}_1x_{i1}+...+\hat{\beta}_kx_{ik})\)</span>. Un estimador consistente de <span class="math inline">\(\sigma^2=(n-k-1)^{-1}\sum_{i=1}^n\frac{\hat{u}_i^2}{\hat{y}_i}\)</span>, donde la división entre <span class="math inline">\(\hat{y}_i\)</span> es el ajuste apropiado de heterocedasticidad y <span class="math inline">\(n-k-1=gl\)</span> dadas las <span class="math inline">\(n\)</span> observaciones y <span class="math inline">\(k+1\)</span> estimadores <span class="math inline">\(\hat{\beta}_0,\hat{\beta}_1,...,\hat{\beta}_k\)</span>. Si <span class="math inline">\(\sigma=\sqrt{\sigma^2}\)</span>, se multiplican los errores estándar Poisson usuales por <span class="math inline">\(\hat{\sigma}\)</span>. Si <span class="math inline">\(\hat{\sigma}\)</span> es notablemente mayor que uno, los errores estándar corregidos pueden ser mucho mayores que los errores estándar nominales, generalmente son incorrectos, de la EMV de Poisson.</p>
<p>Bajo el supuesto de distribución de Poisson, se puede usar el estadístico de la razón de verosimilitudes para probar las restricciones de exclusión, que siempre, tienen la forma de <span class="math inline">\(RV=2(l_{nr}-L_r)\)</span>. Si se tiene <span class="math inline">\(q\)</span> restricciones de exclusión, el estadístico se distribuye aproximadamente con <span class="math inline">\(\chi^2_q\)</span> bajo la hipótesis nula. Bajo el supuesto menos restrictivo de [10], un simple ajuste está disponible si se divide <span class="math inline">\(RV=2(l_{nr}-L_r)\)</span> entre <span class="math inline">\(\sigma^2\)</span> donde <span class="math inline">\(\sigma^2\)</span> se obtiene del modelo no restringido.</p>
</section>
</section>
</section>
<section id="ejemplo-regresión-de-poisson-para-número-de-arrestos" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="ejemplo-regresión-de-poisson-para-número-de-arrestos"><span class="header-section-number">5.2</span> Ejemplo [Regresión de Poisson para número de arrestos]</h2>
<p>La base de datos <strong>crime1</strong> contiene información sobre arrestos durante 1986 y otros datos, sobre 2725 hombres nacidos en California en 1960 o 1961. Cada hombre de la muestra fue arrestado al menos una vez antes 1986.</p>
<p>Las variables:</p>
<ul>
<li><strong>narr86</strong>: indica el número de veces que un hombre fue arrestado durante 1986: esta variable es cero para la mayoría de los hombres de la muestra (72.29%) y varía desde 0 hasta 12. (El porcentaje de hombres detenidos una sola vez durante 1986 es 20.51%)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(wooldridge, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>               tidyverse)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"crime1"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>crime1 <span class="sc">%&gt;%</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2725 obs. of  16 variables:
 $ narr86 : int  0 2 1 2 1 0 2 5 0 0 ...
 $ nfarr86: int  0 2 1 2 1 0 2 3 0 0 ...
 $ nparr86: int  0 0 0 1 0 0 1 5 0 0 ...
 $ pcnv   : num  0.38 0.44 0.33 0.25 0 ...
 $ avgsen : num  17.6 0 22.8 0 0 ...
 $ tottime: num  35.2 0 22.8 0 0 ...
 $ ptime86: int  12 0 0 5 0 0 0 0 9 0 ...
 $ qemp86 : num  0 1 0 2 2 4 0 0 0 3 ...
 $ inc86  : num  0 0.8 0 8.8 8.1 ...
 $ durat  : num  0 0 11 0 1 ...
 $ black  : int  0 0 1 0 0 0 1 0 1 0 ...
 $ hispan : int  0 1 0 1 0 0 0 0 0 1 ...
 $ born60 : int  1 0 1 1 0 1 1 1 1 1 ...
 $ pcnvsq : num  0.1444 0.1936 0.1089 0.0625 0 ...
 $ pt86sq : int  144 0 0 25 0 0 0 0 81 0 ...
 $ inc86sq: num  0 0.64 0 77.44 65.61 ...
 - attr(*, "time.stamp")= chr "25 Jun 2011 23:03"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla de porcentaje</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>crime1 <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">table</span>(narr86)) <span class="sc">%&gt;%</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prop.table</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>narr86
   0    1    2    3    4    5    6    7    9   10   12 
0.72 0.21 0.04 0.02 0.00 0.00 0.00 0.00 0.00 0.00 0.00 </code></pre>
</div>
</div>
<ul>
<li><strong>pcnv</strong>: Es la proporción (no el porcentaje) de detenciones anteriores a 1986 que condujeron a una condena (?)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>crime1 <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">table</span>(pcnv)) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>pcnv
                 0 0.0799999982118607 0.0900000035762787  0.100000001490116 
              1260                  2                  1                  1 
 0.109999999403954  0.129999995231628  0.140000000596046  0.170000001788139 
                 1                  3                  6                 17 
 0.180000007152557  0.200000002980232  0.219999998807907  0.230000004172325 
                 2                 24                  4                  4 
              0.25  0.259999990463257  0.270000010728836   0.28999999165535 
                53                  1                  2                 21 
 0.300000011920929  0.310000002384186  0.319999992847443  0.330000013113022 
                 4                  2                  1                139 
 0.360000014305115  0.379999995231628  0.389999985694885  0.400000005960464 
                 7                 20                  1                 40 
 0.409999996423721  0.419999986886978  0.430000007152557  0.439999997615814 
                 1                  5                 14                 10 
 0.449999988079071  0.469999998807907                0.5  0.529999971389771 
                 4                  3                313                  1 
 0.540000021457672  0.560000002384186  0.569999992847443  0.600000023841858 
                 2                  8                 11                 34 
 0.620000004768372  0.629999995231628  0.639999985694885  0.670000016689301 
                 1                  6                  2                 85 
 0.699999988079071  0.709999978542328  0.730000019073486               0.75 
                 1                  2                  1                 20 
 0.800000011920929  0.829999983310699                  1 
                 8                  3                574 </code></pre>
</div>
</div>
<ul>
<li><strong>avgsen</strong> es la duración promedio de las condenas anteriores cumplidas (cero para la mayoría de casos)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>crime1 <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">table</span>(avgsen)) <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>avgsen
                0 0.300000011920929 0.800000011920929 0.899999976158142 
             2591                 1                 2                 2 
 1.10000002384186  1.39999997615814  2.20000004768372  2.29999995231628 
                5                 1                 1                 1 
 2.59999990463257  2.90000009536743               3.5                 4 
                2                 1                 1                 2 
 4.30000019073486  4.80000019073486  4.90000009536743               5.5 
                1                 1                 1                 2 
 5.59999990463257                 6  6.09999990463257  6.19999980926514 
                4                 1                 2                 1 
 6.30000019073486  6.69999980926514  6.90000009536743  7.09999990463257 
                1                 1                 1                 3 
 7.19999980926514  7.59999990463257  7.80000019073486  7.90000009536743 
                1                 1                 2                 1 
 8.10000038146973  8.19999980926514  8.30000019073486  8.39999961853027 
                1                 1                 1                 1 
 8.60000038146973  8.89999961853027                 9  9.10000038146973 
                2                 1                 2                 1 
 9.30000019073486               9.5  9.60000038146973  9.69999980926514 
                1                 1                 1                 2 
 9.80000019073486  9.89999961853027                10              10.5 
                1                 1                 1                 1 
 10.6000003814697  10.6999998092651  10.8999996185303                11 
                1                 1                 2                 1 
 11.1000003814697  11.3000001907349  11.3999996185303  11.6000003814697 
                1                 1                 1                 2 
 11.6999998092651  11.8000001907349  11.8999996185303  12.1000003814697 
                1                 2                 3                 1 
 12.1999998092651  12.3999996185303              12.5  12.6999998092651 
                2                 1                 2                 1 
 12.8999996185303  13.3000001907349  13.3999996185303  13.6999998092651 
                1                 1                 1                 1 
 14.1999998092651  14.3000001907349  14.3999996185303  14.8000001907349 
                1                 1                 1                 1 
               15  15.6999998092651                16  16.1000003814697 
                1                 1                 1                 1 
 16.2000007629395              16.5  16.6000003814697                17 
                1                 1                 1                 1 
 17.1000003814697  17.6000003814697  17.7000007629395  18.3999996185303 
                1                 1                 1                 3 
             18.5  18.7000007629395  18.8999996185303  19.2999992370605 
                1                 1                 2                 2 
 20.2999992370605  20.6000003814697  21.7000007629395  21.7999992370605 
                1                 1                 1                 1 
               22  22.7999992370605              23.5  23.8999996185303 
                1                 1                 1                 1 
 24.3999996185303  24.6000003814697  30.3999996185303  31.2999992370605 
                1                 2                 1                 1 
 31.7000007629395  31.8999996185303  35.4000015258789  36.0999984741211 
                1                 1                 1                 1 
               39              40.5  47.0999984741211  59.2000007629395 
                1                 1                 1                 1 </code></pre>
</div>
</div>
<ul>
<li><strong>tottime</strong>: tiempo en prisión desde los 18 años (meses)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>crime1 <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">table</span>(tottime)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tottime
                0 0.300000011920929 0.800000011920929 0.899999976158142 
             2591                 1                 2                 2 
 1.10000002384186  1.39999997615814  2.20000004768372  2.29999995231628 
                5                 1                 1                 1 
 2.59999990463257  2.90000009536743                 4  4.80000019073486 
                2                 1                 2                 1 
              5.5  5.59999990463257                 6  6.19999980926514 
                1                 2                 1                 1 
 6.69999980926514                 7  7.09999990463257  7.19999980926514 
                1                 1                 1                 1 
 7.59999990463257  7.80000019073486  8.10000038146973  8.19999980926514 
                1                 1                 1                 1 
 8.30000019073486  8.60000038146973  8.89999961853027                 9 
                1                 2                 1                 1 
 9.10000038146973  9.30000019073486               9.5  9.60000038146973 
                1                 1                 1                 1 
 9.80000019073486  9.89999961853027              10.5  10.8999996185303 
                1                 1                 1                 1 
               11  11.1000003814697  11.1999998092651  11.3000001907349 
                2                 1                 1                 1 
 11.3999996185303  11.6000003814697  11.6999998092651  11.8000001907349 
                1                 1                 1                 1 
 11.8999996185303  12.1999998092651  12.3999996185303              12.5 
                3                 4                 1                 2 
 12.8999996185303  13.3000001907349  13.3999996185303  13.6999998092651 
                1                 1                 1                 1 
 14.1999998092651  14.3000001907349  14.3999996185303  14.6999998092651 
                2                 1                 1                 1 
 15.6999998092651  16.1000003814697              16.5  16.6000003814697 
                1                 1                 1                 1 
 16.7999992370605                17  17.1000003814697                18 
                1                 1                 1                 1 
 18.3999996185303              18.5  18.8999996185303  19.2999992370605 
                2                 1                 2                 2 
 19.3999996185303                20  20.2999992370605  20.7000007629395 
                1                 1                 1                 1 
 21.2000007629395  21.2999992370605  21.3999996185303  21.7000007629395 
                1                 1                 1                 1 
 21.7999992370605                22  22.3999996185303  22.7999992370605 
                1                 1                 1                 1 
 23.2000007629395              23.5  23.7000007629395  23.8999996185303 
                1                 1                 1                 1 
 24.2000007629395  24.3999996185303  24.6000003814697  25.2000007629395 
                1                 1                 1                 1 
 25.7999992370605  29.1000003814697  29.6000003814697                30 
                1                 1                 1                 1 
 30.3999996185303  31.2000007629395  31.2999992370605  31.8999996185303 
                1                 1                 1                 1 
               32  32.4000015258789  35.2000007629395  35.4000015258789 
                1                 1                 1                 3 
 36.0999984741211  36.7999992370605  37.4000015258789  38.0999984741211 
                1                 1                 1                 1 
               39              40.5  41.2000007629395  43.5999984741211 
                1                 1                 1                 1 
 47.0999984741211  49.2000007629395  59.2000007629395  63.4000015258789 
                1                 1                 1                 1 </code></pre>
</div>
</div>
<ul>
<li><strong>ptime86</strong>: es el tiempo en meses que se ha pasado en prisión durante 1986</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>crime1 <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">table</span>(ptime86)) <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ptime86
   0    1    2    3    4    5    6    7    8    9   10   11   12 
2594    7   15    8    7    5   10    7    2    4    4    4   58 </code></pre>
</div>
</div>
<ul>
<li><strong>qemp86</strong>: es la cantidad de trimestres que la persona tuvo empleo en 1986 (de cero a cuatro)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>crime1 <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">table</span>(qemp86)) <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>qemp86
                0 0.600000023841858 0.899999976158142                 1 
              648                 1                 1               294 
 1.39999997615814  1.60000002384186  1.70000004768372  1.79999995231628 
                1                 1                 1                 3 
                2  2.09999990463257                 3  3.40000009536743 
              337                 1               437                 1 
                4 
              999 </code></pre>
</div>
</div>
<ul>
<li><p><strong>ince86</strong>: ingresos legales, 1986, $100s</p></li>
<li><p><strong>black</strong> 1 si es negro, cero otro caso</p></li>
<li><p><strong>hispan</strong> 1 si es hispano, cero otro caso</p></li>
<li><p><strong>born60</strong> 1 nacido en 1960, cero otro caso</p></li>
</ul>
<section id="modelo-de-regresión-poisson" class="level4" data-number="5.2.0.1">
<h4 data-number="5.2.0.1" class="anchored" data-anchor-id="modelo-de-regresión-poisson"><span class="header-section-number">5.2.0.1</span> Modelo de regresión Poisson</h4>
<p><span class="math display">\[
\begin{aligned}
E[narr86|\mathbf{x}]=exp\left(\beta_0+\beta_1pcnv+\beta_2avgsen+\beta_3tottime\\
+\beta_4ptime86+\beta_5qemp86+\beta_6ince86+\\
+\delta_1black+\delta_2hispan+\delta_3born\right)
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprobar la variable de conteo</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>crime1 <span class="sc">%&gt;%</span> </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">table</span>(narr86)) <span class="sc">%&gt;%</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>narr86
   0    1    2    3    4    5    6    7    9   10   12 
1970  559  121   42   12   13    4    1    1    1    1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la variable</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(crime1, <span class="fu">aes</span>(<span class="at">x =</span> narr86)) <span class="sc">+</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, </span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histograma con densidad de kernel del número de arrestos"</span>, </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Valor"</span>, <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span> </span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap3_files/figure-html/ajuste-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ajustar el modelo usando MCO</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>narr86.MCO <span class="ot">&lt;-</span> <span class="fu">lm</span>(narr86<span class="sc">~</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                   pcnv<span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                   avgsen<span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                   tottime<span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                   ptime86<span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                   qemp86<span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                   inc86<span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>                   black<span class="sc">+</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>                   hispan<span class="sc">+</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">I</span>(hispan<span class="sc">*</span>black)<span class="sc">+</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>                   born60,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>                 crime1)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>narr86.MCO2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(narr86<span class="sc">~</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>                   hispan,</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>                 crime1)</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(narr86.MCO, narr86.MCO2,<span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================================
                                  Dependent variable:               
                    ------------------------------------------------
                                         narr86                     
                              (1)                      (2)          
--------------------------------------------------------------------
pcnv                       -0.132***                                
                            (0.040)                                 
                                                                    
avgsen                       -0.011                                 
                            (0.012)                                 
                                                                    
tottime                      0.012                                  
                            (0.009)                                 
                                                                    
ptime86                    -0.041***                                
                            (0.009)                                 
                                                                    
qemp86                     -0.051***                                
                            (0.014)                                 
                                                                    
inc86                      -0.001***                                
                            (0.0003)                                
                                                                    
black                       0.327***                                
                            (0.045)                                 
                                                                    
hispan                      0.194***                0.110***        
                            (0.040)                  (0.040)        
                                                                    
I(hispan * black)                                                   
                                                                    
                                                                    
born60                       -0.022                                 
                            (0.033)                                 
                                                                    
Constant                    0.577***                0.380***        
                            (0.038)                  (0.019)        
                                                                    
--------------------------------------------------------------------
Observations                 2,725                    2,725         
R2                           0.072                    0.003         
Adjusted R2                  0.069                    0.002         
Residual Std. Error    0.829 (df = 2715)        0.858 (df = 2723)   
F Statistic         23.572*** (df = 9; 2715) 7.671*** (df = 1; 2723)
====================================================================
Note:                                    *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>El modelo MCO supone que la variable <span class="math inline">\(y\)</span> es cuantitativa aproximadamente continua, tenemos una variable de conteo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(narr86.MCO<span class="sc">$</span>fitted.values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-0.4978  0.2346  0.4092  0.4044  0.5541  1.0210 </code></pre>
</div>
</div>
<p>No esta ajustando bien, pues arroja valores ajustados negativos el modelo MCO, recordar que la variable <span class="math inline">\(y\)</span> es de conteo y comienza en cero y termina en 12</p>
<p><strong>Ajuste con el modelo Poisson</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>narr86.poisson <span class="ot">&lt;-</span> <span class="fu">glm</span>(narr86<span class="sc">~</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                   pcnv<span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                   avgsen<span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                   tottime<span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                   ptime86<span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>                   qemp86<span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>                   inc86<span class="sc">+</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>                   black<span class="sc">+</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>                   hispan<span class="sc">+</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>                   born60,</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>                 crime1,</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>))</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparo el modelo Possion y MCO</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(narr86.MCO, narr86.poisson, </span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">"text"</span>,</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>          <span class="at">df=</span>F,</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>          <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Tabla 1. Determinantes del número de arrestos de hombres jóvenes"</span>,</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>          <span class="at">dep.var.caption =</span> <span class="st">"Variable dependiente: Número de arrestos"</span>,</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>          <span class="at">header =</span> F,</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>          <span class="at">column.labels =</span> <span class="fu">c</span>(<span class="st">"MCO"</span>, <span class="st">"Poisson"</span>),</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>          <span class="at">model.names =</span> F,</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>          <span class="at">report =</span> <span class="st">"vct*"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Tabla 1. Determinantes del número de arrestos de hombres jóvenes
=============================================================
                    Variable dependiente: Número de arrestos 
                    -----------------------------------------
                                     narr86                  
                            MCO                Poisson       
                            (1)                  (2)         
-------------------------------------------------------------
pcnv                       -0.132               -0.402       
                       t = -3.264***        t = -4.726***    
                                                             
avgsen                     -0.011               -0.024       
                         t = -0.926           t = -1.192     
                                                             
tottime                    0.012                0.024        
                         t = 1.279            t = 1.660*     
                                                             
ptime86                    -0.041               -0.099       
                       t = -4.638***        t = -4.763***    
                                                             
qemp86                     -0.051               -0.038       
                       t = -3.542***          t = -1.310     
                                                             
inc86                      -0.001               -0.008       
                       t = -4.261***        t = -7.762***    
                                                             
black                      0.327                0.661        
                        t = 7.199***         t = 8.950***    
                                                             
hispan                     0.194                0.500        
                        t = 4.880***         t = 6.761***    
                                                             
I(hispan * black)                                            
                                                             
                                                             
born60                     -0.022               -0.051       
                         t = -0.675           t = -0.797     
                                                             
Constant                   0.577                -0.600       
                       t = 15.215***        t = -8.916***    
                                                             
-------------------------------------------------------------
Observations               2,725                2,725        
R2                         0.072                             
Adjusted R2                0.069                             
Log Likelihood                                -2,248.761     
Akaike Inf. Crit.                             4,517.522      
Residual Std. Error        0.829                             
F Statistic              23.572***                           
=============================================================
Note:                             *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(crime1<span class="sc">$</span>narr86)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4044037</code></pre>
</div>
</div>
<p>Es común en los modelos <strong>Poisson</strong> que exista un mal cálculo de los errores estándar, pues puede haber sobre o sub dispersión de la varianza de acuerdo a la ecuación [10]</p>
</section>
<section id="estimación-de-sigma2" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="estimación-de-sigma2"><span class="header-section-number">5.2.1</span> Estimación de <span class="math inline">\(\sigma^2\)</span></h3>
<p>Recordemos la ecuación:</p>
<p><span class="math display">\[\sigma^2=(n-k-1)^{-1}\Sigma_{i=1}^n\frac{\widehat{u}_i^2}{\widehat{y}_i} [11]\]</span> También recordar la ecuación para los residuales</p>
<p><span class="math display">\[\widehat{u}_i=y_i-\widehat{y}_i [12]\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>residuales <span class="ot">&lt;-</span> narr86.poisson<span class="sc">$</span>y<span class="sc">-</span> narr86.poisson<span class="sc">$</span>fitted.values</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>sigma2<span class="ot">&lt;-</span>(<span class="fu">sum</span>(residuales<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>narr86.poisson<span class="sc">$</span>fitted.values))<span class="sc">/</span>narr86.MCO[[<span class="st">"df.residual"</span>]]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>sigma2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.516788</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>raiz.sigma <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sigma2)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>raiz.sigma</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.23158</code></pre>
</div>
</div>
<p>Comprobamos que en este caso <span class="math inline">\(\widehat{\sigma}^2\approx1.52&gt;1\)</span>, entonces existe <strong>sobredispersión</strong> por lo que no se cumple la [9] <span class="math inline">\(Var(y|\mathbf{X})=E(y|\mathbf{X})\)</span>. Por lo tanto, se esta analizando con la <strong>ECMV</strong></p>
</section>
<section id="ajustar-los-errores-estándar" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="ajustar-los-errores-estándar"><span class="header-section-number">5.2.2</span> Ajustar los errores estándar</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>ees.ajustados<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(narr86.MCO, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                    raiz.sigma<span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(narr86.poisson, <span class="at">type =</span> <span class="st">"HC1"</span>))))</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(narr86.MCO, narr86.poisson, </span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">"text"</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">df=</span>F,</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Tabla 2. Determinantes del número de arrestos de hombres jóvenes (ESHRA)"</span>,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">dep.var.caption =</span> <span class="st">"Variable dependiente: Número de arrestos"</span>,</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">header =</span> F,</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">column.labels =</span> <span class="fu">c</span>(<span class="st">"Lineal MCO"</span>, <span class="st">"Exponecial ECMV-Poisson"</span>),</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">model.names =</span> F,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">se=</span>ees.ajustados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Tabla 2. Determinantes del número de arrestos de hombres jóvenes (ESHRA)
=============================================================
                    Variable dependiente: Número de arrestos 
                    -----------------------------------------
                                     narr86                  
                       Lineal MCO     Exponecial ECMV-Poisson
                           (1)                  (2)          
-------------------------------------------------------------
pcnv                    -0.132***            -0.402***       
                         (0.034)              (0.125)        
                                                             
avgsen                   -0.011               -0.024         
                         (0.014)              (0.029)        
                                                             
tottime                   0.012                0.024         
                         (0.013)              (0.025)        
                                                             
ptime86                 -0.041***            -0.099***       
                         (0.007)              (0.028)        
                                                             
qemp86                  -0.051***             -0.038         
                         (0.014)              (0.042)        
                                                             
inc86                   -0.001***            -0.008***       
                        (0.0002)              (0.002)        
                                                             
black                   0.327***             0.661***        
                         (0.058)              (0.123)        
                                                             
hispan                  0.194***             0.500***        
                         (0.040)              (0.114)        
                                                             
I(hispan * black)                                            
                                                             
                                                             
born60                   -0.022               -0.051         
                         (0.032)              (0.100)        
                                                             
Constant                0.577***             -0.600***       
                         (0.043)              (0.110)        
                                                             
-------------------------------------------------------------
Observations              2,725                2,725         
R2                        0.072                              
Adjusted R2               0.069                              
Log Likelihood                              -2,248.761       
Akaike Inf. Crit.                            4,517.522       
Residual Std. Error       0.829                              
F Statistic             23.572***                            
=============================================================
Note:                             *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
</section>
<section id="interpretación" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="interpretación"><span class="header-section-number">5.2.3</span> Interpretación</h3>
<p>Como se puede ver en la Tabla 2 los errores estándar MCO y Poisson son heterocedasticos-robustos. Los errores estándar de Poisson han sido multiplicados por el valor de sigma <span class="math inline">\(\widehat\sigma=1.232\)</span>, lo cual incide sobre la prueba <span class="math inline">\(t\)</span> y por ende en su significancia estadística.</p>
<p>Los coeficientes del MCO y Poisson no son comparables directamente y tienen significados muy diferentes. Por ejemplo, el coeficiente de <em>pcnv</em> implica que, si <span class="math inline">\(\vartriangle{pcnv}=0.10\)</span> el número esperado de arrestos deciende en 0.013 (<span class="math inline">\(0.10\times0.132\approx0.013\)</span>) (<em>pcnv</em> es la proporcion de arrestos previos que desembocaron en una condena). El coeficiente de Poisson implica que <span class="math inline">\(\Delta{pcnv}=0.10\)</span> reduce los arresto en cerca de 4% <span class="math inline">\([0.402\times0.10\approx 0.0402]\)</span> y se multiplica esto por el 100% para obtener el efecto porcentual. Como cuestión de políticas, esto siguiere que se pueden reducir los arrestos generales en 4% si se incremente la probabilidad de condena en 0.10.</p>
<p>El coeficiente de Poisson de <strong>black</strong> implica que, <em>ceteris paribus</em>, el número esperado de arrestos para los hombres negros se estima cerca de <span class="math inline">\(100\times[exp(0.661)-1]\approx93.7\)</span>, es decir que la probabilidad de arrestos para los hombres negros es 93.7% mayor que para los hombres blancos con los mismos valores de las variables explicativas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>hispan<span class="ot">&lt;-</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(narr86.poisson)[<span class="dv">9</span>])<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>hispan</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  hispan 
64.84134 </code></pre>
</div>
</div>
<p>El coeficiente de Poisson de <strong>hispan</strong> implica que, <em>ceteris paribus</em>, el número esperado de arrestos para los hombres hispanos se estima cerca de <span class="math inline">\(100\times[exp(0.5)-1]\approx 64.84\)</span>, es decir que la probabilidad de arrestos para los hombres hispanos es 64.87% mayor que para los hombres no hispanos con los mismos valores de las variables explicativas.</p>
</section>
<section id="efectos-marginales-de-la-regresión-exponencial-emcv-poisson" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="efectos-marginales-de-la-regresión-exponencial-emcv-poisson"><span class="header-section-number">5.2.4</span> Efectos marginales de la Regresión Exponencial EMCV-Poisson</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mfx)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">poissonmfx</span>(narr86<span class="sc">~</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                  pcnv<span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                  avgsen<span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>                  tottime<span class="sc">+</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>                  ptime86<span class="sc">+</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>                  qemp86<span class="sc">+</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>                  inc86<span class="sc">+</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>                  black<span class="sc">+</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>                  hispan<span class="sc">+</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>                  born60,</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>               crime1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
poissonmfx(formula = narr86 ~ pcnv + avgsen + tottime + ptime86 + 
    qemp86 + inc86 + black + hispan + born60, data = crime1)

Marginal Effects:
              dF/dx   Std. Err.       z     P&gt;|z|    
pcnv    -0.13218998  0.02770671 -4.7710 1.833e-06 ***
avgsen  -0.00782541  0.00656405 -1.1922   0.23320    
tottime  0.00806178  0.00485401  1.6608   0.09674 .  
ptime86 -0.03244365  0.00677624 -4.7879 1.686e-06 ***
qemp86  -0.01251507  0.00960118 -1.3035   0.19241    
inc86   -0.00266002  0.00031733 -8.3825 &lt; 2.2e-16 ***
black    0.27712004  0.03843968  7.2092 5.627e-13 ***
hispan   0.19144813  0.03242309  5.9047 3.533e-09 ***
born60  -0.01668211  0.02079586 -0.8022   0.42245    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

dF/dx is for discrete change for the following variables:

[1] "black"  "hispan" "born60"</code></pre>
</div>
</div>
</section>
<section id="interpretaciones" class="level3" data-number="5.2.5">
<h3 data-number="5.2.5" class="anchored" data-anchor-id="interpretaciones"><span class="header-section-number">5.2.5</span> Interpretaciones:</h3>
<ul>
<li>Como se puede observar los efectos marginales de Poisson ya son comparables a los coeficientes de MCO, de tal manera que, el <strong>EPP</strong> de Poisson para la variables <strong>pcnv</strong> es igual al coeficiente de MCO, es decir ambos son de <strong>-0.13</strong> aproximadamente. Donde existe diferencias marcadas entre el <strong>EPP</strong> y coeficiente de MCO es en <strong>black</strong> y en <strong>hispan</strong>. De la misma manera que se hizo en las interpretaciones de la Tabla 2 se debe aproximar mejor el efecto parcial de las variables binarias usando la ecuación [4]. Por ejemplo para <strong>black</strong>:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>black.epp <span class="ot">&lt;-</span><span class="dv">100</span><span class="sc">*</span>(<span class="fu">exp</span>(<span class="fl">0.27712004</span>)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>black.epp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31.93247</code></pre>
</div>
</div>
<p>El coeficiente de Poisson de <strong>black</strong> de los efectos marginales implica que, <em>ceteris paribus</em>, el número esperado de arrestos para los hombres negros se estima cerca de <span class="math inline">\(100\times[exp(0.2771)-1]\approx31.93\)</span>, es decir que el porcentaje de arrestos para los hombres negros es 31.93% mayor que para los hombres blancos con los mismos valores de las variables explicativas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>hispan.epp <span class="ot">&lt;-</span><span class="dv">100</span><span class="sc">*</span>(<span class="fu">exp</span>(<span class="fl">0.19144813</span>)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>hispan.epp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.1002</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./cap2.html" class="pagination-link" aria-label="Modelo Tobit">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelo Tobit</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./cap4.html" class="pagination-link" aria-label="Modelo de Dos Partes">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelo de Dos Partes</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>